version: "1.1"
services:
  apache:
    image: php:8.2-apache
    ports:
      - 8001:80
    build:
      args:
        user: myaac
        uid: 1000
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
    networks:
      - default

  db:
    image: mysql:8.0
    restart: unless-stopped # always?
    environment:
      MYSQL_DATABASE: myaac
      MYSQL_ROOT_PASSWORD: root
      #MYSQL_RANDOM_ROOT_PASSWORD: '1' #doesnt work
      MYSQL_PASSWORD: myaac
      MYSQL_USER: myaac
    ports:
      - 8003:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8002:80

volumes:
  db:
